### PR TITLE
added footer with social icons, will sort images into folder later

### LINKED ISSUE #9: Footer

### PR DESCRIPTION
**Pull request by michaelclark2**
Closes #9 

@RitaSyed  suggests that we make the links actually have an href, i left them blank because i wasnt sure if we should actually link them

### CODE REVIEW

**Comment by RitaSyed** [comment]
Looks good!

**Comment by michaelclark2** [comment]
where should we link the href in the footer? just to facebook.com twitter.com and youtube.com?

**Comment by michaelclark2** [comment]
let me find a funny youtube video before you merge this

**Comment by RitaSyed** [comment]
Ok, you can merge it yourself after you find the videos.

**Comment by RitaSyed** [comment]
Also, let’s talk on Thursday more about color palettes that fit to the band website theme.

**Comment by Mehret17** [comment]
Yes we stated in our tickets that they should take us to the page when we click them 
image

**Comment by Mehret17** [comment]
👍

**Pull request merged**
